"""Stage 4 -- HTML Renderer.

A renderer, not a writer (Ingrid's review, must-fix #3): this stage
consumes a complete PipelineDocument and materializes it as HTML. It does
not generate new prose or new specs -- any judgment call it can't resolve
mechanically (e.g. a visual that failed validation) is logged to
global_notes and shown as a visible placeholder, never silently dropped or
silently fixed by re-invoking an LLM.

v1 targets a single self-contained HTML file, Vega-Lite rendered
client-side via CDN (vega-embed) -- no build step. This is design principle
#4's first concrete step, explicitly short of its full ambition (no zoom-
as-navigation, no motion, no true multi-dimensional/spatial views yet --
see the Sprint 8 prototype proposal for why this step was chosen anyway).
"""
import copy
import html
import json

from prototype.pipeline.schema import PipelineDocument

# Vega-Lite specs generated by the Stage 2 LLM tend to hardcode a fixed
# pixel width (e.g. 820) chosen without any knowledge of the actual page
# layout -- on Sprint 8's first real runs this made charts overflow the
# content column, which is narrower than 820px once the nav sidebar and
# padding are accounted for. The renderer's job is to materialize content
# correctly regardless of what Stage 2 assumed about its own container, so
# the fix belongs here, not in Stage 2.
#
# First attempt used "width": "container" + autosize, which is the "correct"
# Vega-Lite-native way to do this -- but it depends on the embedding div
# having a resolved CSS width at the moment vega-embed reads it, and has
# known inconsistent support across composite view types (layer/facet/
# concat). It silently failed in a real browser (no charts rendered at all,
# not just wrong-sized ones) in a way this environment can't catch without
# an actual browser -- caught only because the founder opened the file and
# reported it, not by any automated check here. Replaced with something
# that doesn't depend on vega-embed's container-sizing behavior at all:
# clamp every explicit numeric width to a safe static maximum that's known
# to fit the content column. Less elegant, much less likely to silently
# break.
_COMPOSITE_KEYS = ("layer", "concat", "hconcat", "vconcat", "facet", "repeat")
_MAX_CHART_WIDTH = 640  # safely inside the ~750-770px content column at 1100px page width


def _clamp_widths(node) -> None:
    """Recursively cap any numeric 'width' key to _MAX_CHART_WIDTH, in
    place. Only touches numeric widths -- never introduces "container" or
    any autosize behavior, to avoid the exact failure mode above."""
    if isinstance(node, dict):
        w = node.get("width")
        if isinstance(w, (int, float)) and w > _MAX_CHART_WIDTH:
            node["width"] = _MAX_CHART_WIDTH
        for v in node.values():
            _clamp_widths(v)
    elif isinstance(node, list):
        for item in node:
            _clamp_widths(item)


def _make_responsive(spec: dict) -> dict:
    spec = copy.deepcopy(spec)
    if isinstance(spec.get("width"), (int, float)):
        spec["width"] = min(spec["width"], _MAX_CHART_WIDTH)
    else:
        spec.setdefault("width", _MAX_CHART_WIDTH)
    _clamp_widths(spec)
    return spec

VEGA_CDN = """<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>"""

STYLE = """
<style>
  :root { --ink:#14181a; --ink-mid:#3c4547; --ink-light:#6d7679; --rule:#dadfde;
          --accent:#20795b; --accent2:#a16a17; --cream:#ffffff; --cream-dark:#f4f1ea; }
  * { box-sizing: border-box; }
  body { margin:0; font-family: Georgia, 'Iowan Old Style', serif; color:var(--ink);
         background:var(--cream); line-height:1.65; }
  .layout { display:flex; max-width:1100px; margin:0 auto; }
  nav { position:sticky; top:0; align-self:flex-start; width:220px; padding:2.5rem 1.5rem;
        border-right:1px solid var(--rule); height:100vh; overflow-y:auto; }
  nav a { display:block; font-size:0.85rem; color:var(--ink-light); text-decoration:none;
          margin-bottom:0.8rem; }
  nav a:hover { color:var(--accent); }
  main { flex:1; padding:2.5rem 2.5rem 6rem; min-width:0; }
  header.doc-header { margin-bottom:3rem; }
  header.doc-header h1 { font-size:1.9rem; margin:0 0 0.6rem; }
  .meta { font-size:0.85rem; color:var(--ink-light); }
  section.content-section { margin-bottom:3.5rem; scroll-margin-top:1rem; }
  section.content-section h2 { font-size:1.3rem; border-bottom:1px solid var(--rule);
                                padding-bottom:0.5rem; margin:0 0 1.2rem; }
  .prose p { color:var(--ink-mid); margin:0 0 1rem; }
  .visual-block { margin:1.5rem 0; border:1px solid var(--rule); border-radius:6px;
                  padding:1.2rem; background:var(--cream-dark); max-width:100%; overflow-x:auto; }
  .visual-block > div[id^="chart-"] { max-width:100%; }
  .visual-caption { font-size:0.8rem; color:var(--ink-light); margin-top:0.8rem; }
  .illustrative-badge { display:inline-block; font-size:0.65rem; font-weight:700;
                         letter-spacing:0.05em; text-transform:uppercase; color:var(--accent2);
                         background:rgba(161,106,23,0.12); padding:0.15em 0.5em; border-radius:3px;
                         margin-bottom:0.6rem; }
  .visual-failed { border-color:#b3453a; background:#fdf0ee; color:#8a2f27; padding:1rem;
                   font-size:0.85rem; }
  .global-notes { margin-top:4rem; padding-top:1.5rem; border-top:1px solid var(--rule);
                   font-size:0.8rem; color:var(--ink-light); }
</style>
"""


def _render_visual(vs, section_id: str) -> str:
    if not vs.spec or not vs.validation_passed:
        return (
            f'<div class="visual-block visual-failed">'
            f'⚠ Visual "{html.escape(vs.caption)}" could not be rendered '
            f"(generation or validation failed). Flagged, not silently dropped."
            f"</div>"
        )
    if vs.content_grounded is False:
        issues = "; ".join(vs.grounding_issues) or "content did not match the section topic"
        return (
            f'<div class="visual-block visual-failed">'
            f'⚠ Visual "{html.escape(vs.caption)}" was structurally valid but failed the '
            f"content-grounding check ({html.escape(issues)}). Withheld rather than shown, "
            f"since a technically-correct-but-off-topic chart is worse than none."
            f"</div>"
        )
    chart_div_id = f"chart-{section_id}-{vs.slot_id}"
    spec_json = json.dumps(_make_responsive(vs.spec))
    illustrative_badge = '<div class="illustrative-badge">Illustrative data — not retrieved from live sources</div>' if vs.illustrative else ""
    return f"""<div class="visual-block">
  {illustrative_badge}
  <div id="{chart_div_id}"></div>
  <div class="visual-caption">{html.escape(vs.caption)}</div>
  <script>vegaEmbed('#{chart_div_id}', {spec_json}, {{actions: false}});</script>
</div>"""


def render(doc: PipelineDocument) -> str:
    nav_links = "\n".join(f'<a href="#{s.id}">{html.escape(s.title)}</a>' for s in doc.sections)

    sections_html = []
    for section in doc.sections:
        prose_html = "\n".join(f"<p>{html.escape(p)}</p>" for p in section.prose_blocks)
        visuals_html = "\n".join(_render_visual(vs, section.id) for vs in section.visual_slots)
        sections_html.append(f"""<section class="content-section" id="{section.id}">
  <h2>{html.escape(section.title)}</h2>
  <div class="prose">{prose_html}</div>
  {visuals_html}
</section>""")

    notes_html = ""
    if doc.global_notes:
        items = "\n".join(f"<li>{html.escape(n)}</li>" for n in doc.global_notes)
        notes_html = f'<div class="global-notes"><strong>Pipeline notes:</strong><ul>{items}</ul></div>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(doc.title)}</title>
{VEGA_CDN}
{STYLE}
</head>
<body>
<div class="layout">
  <nav>{nav_links}</nav>
  <main>
    <header class="doc-header">
      <h1>{html.escape(doc.title)}</h1>
      <p class="meta">Audience: {html.escape(doc.audience)} &middot; Goal: {html.escape(doc.goal)}<br>
      Generated {html.escape(doc.generated_at)} by Altair8's Sprint 8 prototype pipeline.</p>
    </header>
    {''.join(sections_html)}
    {notes_html}
  </main>
</div>
</body>
</html>
"""
